global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'crossbring-rt-engine'
    static_configs:
      # Docker Desktop exposes host as host.docker.internal
      - targets: ['host.docker.internal:9100']

